### PR TITLE
Bootstrap-news week clone milestone2

### PR DESCRIPTION
**Pull request by fortuneonyeka**
Bootstrap news week clone milestone2

### CODE REVIEW

**Review by SajjadAhmad14 — CHANGES_REQUESTED** [review]
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello! You  both have been doing a tremendous job so far :ok_hand:
### But there are some changes to make in order to get your project approved.

-  [x]  Top Story in column two does not have image and text, please see the original page and fix it accordingly!

Your page:
yours
Orignal:
orignal

- [x] Top Story and Featured Stories are just headings, but not links. So please make them headings instead of links. 
- [x] Please make images in Featured stories, and Sponsored insights clickable links. Moreover, the title text has a text-decoration on hover, and the text color should remain the same.
- [x]  Please make images in More Stories, and Latest news clickable links and add text-decoration underline to the title text.
- [x]  Please fix this: 
broken

### For each piece of news
- [x] Each image have a link
- [x] Each title uses a hx tag and have a link
- [x] Your navbar is missing the toggle button on the small and medium viewport.
Your navbar:
nav-yours
Orignal navbar:
nav-orignal

- [x] Navbar on an extra small device is not the same as the original.
Yours:
broken-img
Orignal:
nav-orignal
  
# Optional

- [x] There should be more margin between the footer and section above it.
- [ ] Please update the screenshot of your project in README accordingly.
- [ ] README file should be free from grammar and spelling mistakes. You can use [Grammarly](https://app.grammarly.com/) to identify mistakes and correct them.

### Reminder: 
"As described in the Code reviews limit Policy you have 2 code reviews left for this project."

## Happy Coding!

## You can always connect with me on slack ( @Sajjad Ahmad).

**Comment by fortuneonyeka** [comment]
> # Changes Required ♻️
> > "Change is inevitable. Change is constant. -Benjamin Disraeli"
> 
> ## Hello! You both have been doing a tremendous job so far 👌
> ### But there are some changes to make in order to get your project approved.
> * [ ]   Top Story in column two does not have image and text, please see the original page and fix it accordingly!
> 
> Your page:
> yours
> Orignal:
> orignal
> 
> * [x]  Top Story and Featured Stories are just headings, but not links. So please make them headings instead of links.
> * [x]  Please make images in Featured stories, and Sponsored insights clickable links. Moreover, the title text has a text-decoration on hover, and the text color should remain the same.
> * [x]   Please make images in More Stories, and Latest news clickable links and add text-decoration underline to the title text.
> * [ ]   Please fix this:
>   broken
> 
> ### For each piece of news
> * [x]  Each image have a link
> * [x]  Each title uses a hx tag and have a link
> * [x]  Your navbar is missing the toggle button on the small and medium viewport.
>   Your navbar:
>   nav-yours
>   Orignal navbar:
>   nav-orignal
> * [x]  Navbar on an extra small device is not the same as the original.
>   Yours:
>   broken-img
>   Orignal:
>   nav-orignal
> 
> # Optional
> * [ ]  There should be more margin between the footer and section above it.
> * [ ]  Please update the screenshot of your project in README accordingly.
> * [ ]  README file should be free from grammar and spelling mistakes. You can use [Grammarly](https://app.grammarly.com/) to identify mistakes and correct them.
> 
> ### Reminder:
> "As described in the Code reviews limit Policy you have 2 code reviews left for this project."
> 
> ## Happy Coding!
> ## You can always connect with me on slack ( @sajjad Ahmad).

Hello good evening sir
Thank you very much for your timely review of our code
however we have a few questions
https://fortuneonyeka.github.io/bootstrap-newsweek/
above is the link to my project. the image and text on the second colum, top story is clearly showing. Please i would be glad if you can explain further what you mean by "Top Story in column two does not have image and text, please see the original page and fix it accordingly!"
Thank you very much

**Review by george-shammar — APPROVED** [review]
### **STATUS: APPROVED** :heavy_check_mark: :heavy_check_mark: 

**Congratulations.**  :wine_glass: :wine_glass: 

**Your project is approved, having satisfied the minimum requirements of this milestone.** :ok_hand: :ok_hand: 

**Thank you for implementing the required changes from the previous review.**

**Good job.** :+1: :+1: 

**You can now go ahead and merge this branch.**

**Happy coding!** :computer_mouse: :desktop_computer:

**Comment by SajjadAhmad14** [comment]
Thank you so much for asking me for clarity. I could not find the image and title for the Top Story section, so I did attach a screenshot for that as well! Sorry for the inconvenience!

**Comment by SajjadAhmad14** [comment]
Thank you so much for asking me for clarity. I could not find the image and title for the Top Story section, so I did attach a screenshot for that as well! Sorry for the inconvenience!

**Pull request merged**
