### PR TITLE
News-week

### PR DESCRIPTION
**Pull request by fortuneonyeka**
News-week cloning of the top nav and footer using bootstrap

### CODE REVIEW

**Review by DeliceLydia — CHANGES_REQUESTED** [review]
#  Status: Change Requested

Good job @fortuneonyeka and @marcosmerida good job on working on this first milestone your project is looking quite well so far but you need to make some changes so that it can be approved

## To highlights image

- You used semantic HTML
- Newsweek logo has a link 
- Login change to an icon in the mobile view
- Main navigation uses a nav tag and each option has a link
- Menu hides in mobile view and it shows the humberger button
- Your project is looking nice on all devices

## To improve image

- Subscribe button is supposed to have a link
- the logo and subscribe are not centered on mobile and try to make it look like the original refer to the image below

yours

sub

original

og

- Navbar needs to be improved on desktop view

yours
nav

original
navbar

- Fix your live demo in the README it doesn't work
- Hamburger button doesn't show on tablet work on that
- Footer has everything it supposed to have but you can improve it to look like the original
- You can add .vscode to the gitignore file

## KIndly fix that and always refer to the original to do better and after you will request another CR and remember that you still have only 2 Code reviews and work accordingly

All the best,

Lydia Ingabire

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @fortuneonyeka and @marcosmerida  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your clone almost looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
:+1: All requested changes have been implemented 
#### :warning: However there is a one requested change which is not implemented successfully, don't feel discouraged because of being asked some changes more and more, that's because this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] The previous reviewer asked you to add `.vscode` in .gitignore file, she meant that there shouldn't be a `.vscode` folder in your root directory of your project, so adding it on gitignore didn't remove it from there, it's still there. To remove it completely, run the following command: `git rm -rf .vscode` and commit the changes.
___

_:warning: Reminder: As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561#), when you reach to the limit of 3 code reviews and your project was not approved, you will need to repeat the project. => You are now left with only one (1) chance to get a review on this project. So implement the requested changes very carefully. If you think that the code review was not fair, you can request a second-opinion using [this form](https://airtable.com/shrmBIv6cXYrq4Fgv)._

_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Review by Temmarie — APPROVED** [review]
## Status: Approved :heavy_check_mark:

### Hi @fortuneonyeka and @marcosmerida  ! :wave:

#### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: :tada:
**N.B: All unnecessary files should be added to the /gitignore file, like the DS_store.**

- [ ] Please fix your linter errors.

#### You may move on, good luck with your next projects! :rocket:
#### Happy Coding! :+1:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by fortuneonyeka** [comment]
Thank you very much for your review and approval

**Pull request closed without merging**
